services:
  web:
    container_name: web
    stdin_open: true
    build: ./
    ports:
      - "80:80"
    volumes:
      - type: bind
        source: ./../
        target: /var/www/html/
      - type: bind
        source: ./000-default.conf
        target: /etc/apache2/sites-available/000-default.conf
      - type: bind
        source: ./php.ini-development
        target: /usr/local/etc/php/php.ini-development
  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: TaskManagementSystem
    ports:
      - "5432:5432"