FROM php:8.3.16-apache

RUN apt update \
    && curl -sS https://getcomposer.org/installer -o composer-setup.php \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load \
    && chmod -R 0777 /var/www/html/* \
    && apt -y install libpq-dev \
    && docker-php-ext-install pgsql pdo_pgsql

RUN apt -y install mc